POST http://localhost:8000/order HTTP/1.1
content-type: application/json

{
    "id": "5",
    "price": 2.85,
    "tax": 3.28
}

###
GET http://localhost:8000/order HTTP/1.1
content-type: application/json